# ==============================
# DEV PROFILE
# ==============================

# ==============================
# MySQL
# ==============================

spring.datasource.url=jdbc:mysql://localhost:3306/hrmspolicies_2?useSSL=false&serverTimezone=Asia/Kolkata&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=Shiva@2812
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ==============================
# JPA / Hibernate
# ==============================

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ==============================
# Logging
# ==============================

logging.level.root=INFO
logging.level.com.example.hrmspolicies2=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.springframework.web=INFO