spring.datasource.url=${TEST_DB_URL:jdbc:postgresql://localhost:5432/hrmspolicies_test}
spring.datasource.username=${TEST_DB_USERNAME:}
spring.datasource.password=${TEST_DB_PASSWORD:}

management.endpoints.web.exposure.include=*
management.endpoint.env.show-values=never
management.endpoint.health.show-details=always

logging.level.root=INFO
logging.level.com.example.hrmspolicies2=INFO